name: 🚀 Publish Dokka

on:
  push:
    tags:
      - "*" # Runs on all tag pushes
  workflow_dispatch: # Allows manual trigger

permissions:
  contents: write

jobs:
  dokka:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Important: ensures tags are fetched

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      - name: Grant execute permissions to Gradle wrapper
        run: chmod +x ./gradlew

      - name: Generate and prepare Dokka docs
        run: ./gradlew :koffee:publishDocs

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs
