name: 🚀 Publish Dokka

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  dokka:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      - name: Grant execute permissions to Gradle wrapper
        run: chmod +x ./gradlew

      - name: Generate Dokka HTML docs
        run: ./gradlew :koffee:dokkaHtml

      - name: Add .nojekyll to bypass Jekyll on GitHub Pages
        run: echo > docs/.nojekyll

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs
