name: Run Instrumented Tests on Emulator.wtf

on:
  pull_request:
    branches: [master, dev]
  workflow_dispatch:

jobs:
  instrumented-tests:
    name: Run Instrumented Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: 17

      - name: Set up Gradle
        uses: gradle/actions/setup-gradle@v3

      - name: Build Koffee app and test APKs
        run: ./gradlew clean :koffee:assembleDebug :koffee:assembleDebugAndroidTest

      - name: Run tests on emulator.wtf
        uses: emulator-wtf/run-tests@v0
        with:
          api-token: ${{ secrets.EMULATOR_WTF_API_KEY }}
          app: koffee/build/outputs/apk/debug/koffee-debug.apk
          test: koffee/build/outputs/apk/androidTest/debug/koffee-debug-androidTest.apk
          outputs-dir: build/test-results
