name: Publish to Maven Central

on:
  push:
    tags:
      - "v*.*.*"

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17
          cache: gradle

      - name: Set RELEASE_VERSION from tag
        run: echo "RELEASE_VERSION=${GITHUB_REF#refs/tags/v}" >> $GITHUB_ENV

      - name: Decode GPG key
        run: |
          echo "${{ secrets.GPG_SECRET_KEY }}" | base64 -d > decoded_key.asc
          echo "SIGNING_SECRET_KEY=$(cat decoded_key.asc)" >> $GITHUB_ENV

      - name: Publish to OSSRH
        run: ./gradlew publishReleasePublicationToOSSRHRepository -Psigning.keyId=$SIGNING_KEY_ID -Psigning.secretKey="$SIGNING_SECRET_KEY" -Psigning.password=$SIGNING_PASSWORD -PossrhUsername=$OSSRH_USERNAME -PossrhPassword=$OSSRH_PASSWORD
        env:
          SIGNING_KEY_ID: ${{ secrets.GPG_KEY_ID }}
          SIGNING_SECRET_KEY: ${{ secrets.GPG_SECRET_KEY }} # base64-encoded ASCII-armored key
          SIGNING_PASSWORD: ${{ secrets.GPG_PASSWORD }}
          OSSRH_USERNAME: ${{ secrets.OSSRH_USERNAME }}
          OSSRH_PASSWORD: ${{ secrets.OSSRH_PASSWORD }}
          RELEASE_VERSION: ${{ env.RELEASE_VERSION }}
