name: Publish

on:
  push:
    tags:
      - "v*"


jobs:
  publish:
    name: Release build and publish
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: 17

      - name: Write GPG key file
        run: |
          echo "${{ secrets.GPG_PRIVATE_KEY }}" > gpg-secret.asc


      - name: Publish and release to Maven Central
        run: ./gradlew publishAndReleaseToMavenCentral --no-configuration-cache
        env:
          ORG_GRADLE_PROJECT_mavenCentralUsername: ${{ secrets.JRELEASER_MAVENCENTRAL_USERNAME }}
          ORG_GRADLE_PROJECT_mavenCentralPassword: ${{ secrets.JRELEASER_MAVENCENTRAL_PASSWORD }}
          ORG_GRADLE_PROJECT_signingKeyFile: "${{ github.workspace }}/gpg-secret.asc"
          ORG_GRADLE_PROJECT_signingKeyId: ${{ secrets.GPG_KEY_ID }}
          ORG_GRADLE_PROJECT_signingKeyPassword: ${{ secrets.GPG_PASSWORD }}
