name: Publish to Maven Central

on:
  push:
    tags:
      - "v*.*.*"

jobs:
  publish:
    name: Publish tagged release
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: 'gradle'

      - name: Set RELEASE_VERSION from tag
        run: echo "RELEASE_VERSION=${GITHUB_REF#refs/tags/v}" >> $GITHUB_ENV

      - name: Import GPG key
        run: |
          echo "${{ secrets.GPG_PRIVATE_KEY }}" | base64 -d > $HOME/key.asc
          gpg --batch --import $HOME/key.asc

      - name: Trust GPG key
        run: |
          echo -e "5\ny\n" | gpg --command-fd 0 --edit-key ${{ secrets.GPG_KEY_ID }} trust

      - name: Publish to OSSRH
        run: ./gradlew publishReleasePublicationToOSSRHRepository \
          -Psigning.keyId=${{ secrets.GPG_KEY_ID }} \
          -Psigning.password=${{ secrets.GPG_PASSWORD }}
        env:
          RELEASE_VERSION: ${{ env.RELEASE_VERSION }}
          OSSRH_USERNAME: ${{ secrets.OSSRH_USERNAME }}
          OSSRH_PASSWORD: ${{ secrets.OSSRH_PASSWORD }}
