name: 📝 Draft Release Notes

on:
  push:
    tags:
      - 'v*'

jobs:
  update-release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Generate Release Notes
        uses: release-drafter/release-drafter@v5
        with:
          config-name: release-drafter.yml
          publish: true  # 🔥 auto-publish instead of draft
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
