name: Release Please

on:
  push:
    branches:
      - master

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: google-github-actions/release-please-action@v4
        id: release
        with:
          release-type: java
        continue-on-error: true

      - name: Check if release was created
        if: steps.release.outputs.release_created == 'true'
        run: echo "A new release was created!"
