name: 🔁 Retry GitHub Release

on:
  workflow_dispatch:
    inputs:
      tag:
        description: 'Tag name to create a release for'
        required: true

permissions:
  contents: write

jobs:
  retry-release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Run release-drafter
        uses: release-drafter/release-drafter@v5
        with:
          config-name: release-drafter.yml
          publish: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
