name: Run All Tests

on:
  push:
    branches: ['**']
  pull_request:
    branches: ['**']

jobs:
  unit-tests:
    name: 🧪 Unit Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17 # adjust as needed

      - name: Grant execute permission to Gradle wrapper
        run: chmod +x ./gradlew

      - name: Run unit tests
        run: ./gradlew test

  instrumented-tests:
    name: 📱 Instrumented Tests
    runs-on: macos-latest  # 🧠 Required for Android emulator

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17 # adjust as needed

      - name: Set up Android SDK
        uses: android-actions/setup-android@v3

      - name: Create AVD and launch emulator
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: 30
          target: default
          arch: x86_64
          script: ./gradlew connectedDebugAndroidTest
