name: 🧪 Run Tests

on:
  pull_request:
    branches: ['**']

jobs:
  unit-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 21

      - name: Cache Gradle
        uses: gradle/actions/setup-gradle@v3

      - name: Run common unit tests
        run: ./gradlew jvmTest
