name: 🧪 Run Unit Tests

on:
  pull_request:
    branches: ['**']

jobs:
  unit-tests:
    name: 🧪 Unit Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17 # adjust as needed

      - name: Grant execute permission to Gradle wrapper
        run: chmod +x ./gradlew

      - name: Run unit tests
        run: ./gradlew test
